In [4]:
import six.moves.cPickle as pickle
import gzip
import os
import numpy as np
import numpy.linalg as lin
import scipy.misc
from __future__ import division

In [5]:
def load_data(dataset):
    ''' Loads the dataset

    :type dataset: string
    :param dataset: the path to the dataset (here MNIST)
    
    copied from http://deeplearning.net/ and revised by hchoi
    '''
    # Download the MNIST dataset if it is not present
    data_dir, data_file = os.path.split(dataset)
    if data_dir == "" and not os.path.isfile(dataset):
        # Check if dataset is in the data directory.
        new_path = os.path.join(
            os.path.split(__file__)[0],
            dataset
        )
        if os.path.isfile(new_path) or data_file == 'mnist.pkl.gz':
            dataset = new_path

    if (not os.path.isfile(dataset)) and data_file == 'mnist.pkl.gz':
        from six.moves import urllib
        origin = (
            'http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist.pkl.gz'
        )
        print('Downloading data from %s' % origin)
        urllib.request.urlretrieve(origin, dataset)

    print('... loading data')

    # Load the dataset
    with gzip.open(dataset, 'rb') as f:
        try:
            train_set, valid_set, test_set = pickle.load(f, encoding='latin1')
        except:
            train_set, valid_set, test_set = pickle.load(f)
    # train_set, valid_set, test_set format: tuple(input, target)
    # input is a numpy.ndarray of 2 dimensions (a matrix)
    # where each row corresponds to an example. target is a
    # numpy.ndarray of 1 dimension (vector) that has the same length as
    # the number of rows in the input. It should give the target
    # to the example with the same index in the input.

    return train_set, valid_set, test_set

In [6]:
train_set, val_set, test_set = load_data('C:/test/mnist.pkl.gz')

train_x, train_y = train_set
val_x, val_y = val_set
test_x, test_y = test_set

print(train_x.shape) # 50k * 784
print(train_y.shape) # 50k

'''
for i in range(100):
    samp_img = train_x[i].reshape((28, 28))
    scipy.misc.imsave('test'+str(i)+'.jpg', samp_img)
    print(train_y[i])
'''        

save_path = "G:/내 드라이브/Class/8th/ML\HW1/"

... loading data
(50000, 784)
(50000,)


In [21]:
X = train_x

In [25]:
mu = X.mean(0) 
C = np.cov(X - mu, rowvar=False) 
d, u = np.linalg.eigh(C) 
U = u.T[::-1] 
Z = np.dot(X - mu, U[:2].T) 

In [26]:
Z[0]

array([-0.46150962, -1.24686457])

In [29]:
for i in range(5):
    eig_img = U[i].reshape((28,28)) #(28, 28)
    scipy.misc.imsave(save_path+'train_eig'+str(i)+'.jpg', eig_img)

c:\users\hgh97\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [61]:
len(eig_sam[1][5])

28

In [28]:
len(eig_sam[1])

28

In [9]:
#for saving memory
val_x, val_y, val_set = None, None, None
test_x, test_y, test_set = None, None, None

In [5]:
mean_img = train_x.mean(axis=0) # (784, )
mean_img = mean_img.reshape((28,28)) #(28, 28)
scipy.misc.imsave(save_path+'train_mean.jpg', mean_img)

c:\users\hgh97\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [6]:
var_img = train_x.var(axis=0)
var_img = var_img.reshape((28,28)) #(28, 28)
scipy.misc.imsave(save_path+'train_var.jpg', var_img)

c:\users\hgh97\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [35]:
train_x_T = np.transpose(train_x[0:500])
train_x_dot = np.matmul(train_x[0:500], train_x_T)

In [36]:
print(train_x.shape)
print(train_x_T.shape)

(50000, 784)
(784, 500)


In [37]:
train_x, train_x_t =  None, None

In [38]:
train_x_cov = train_x_dot / 500

In [39]:
train_x_dot =  None

In [40]:
eig_vec = lin.eig(train_x_cov)
eig_val = lin.eigvals(train_x_cov)

In [43]:
eig_val

array([3.55697975e+01, 4.72890902e+00, 3.94693971e+00, 3.15523076e+00,
       2.74155164e+00, 2.52714396e+00, 2.23953390e+00, 1.59169424e+00,
       1.51188898e+00, 1.20584548e+00, 1.18909943e+00, 1.06221390e+00,
       9.51241314e-01, 8.80155981e-01, 8.25557470e-01, 7.71274388e-01,
       7.13400722e-01, 6.82198644e-01, 5.93703270e-01, 5.59066057e-01,
       5.47208428e-01, 5.14329314e-01, 4.99071568e-01, 4.65490401e-01,
       4.33863342e-01, 4.21382815e-01, 4.15956587e-01, 3.89826715e-01,
       3.63606572e-01, 3.59291524e-01, 3.34873170e-01, 3.25867206e-01,
       3.09210032e-01, 2.84510553e-01, 2.78044760e-01, 2.62870401e-01,
       2.58007020e-01, 2.47590944e-01, 2.31585070e-01, 2.28125781e-01,
       2.12058336e-01, 2.09989399e-01, 2.05978841e-01, 2.01669902e-01,
       1.97041109e-01, 1.83932647e-01, 1.78997800e-01, 1.75045386e-01,
       1.68066144e-01, 1.62381753e-01, 1.55145317e-01, 1.51516095e-01,
       1.42961800e-01, 1.39363125e-01, 1.35088027e-01, 1.31155178e-01,
      

In [55]:
X = [[4,2],[3,5]]
lin.eig(X)

(array([2., 7.]), array([[-0.70710678, -0.5547002 ],
        [ 0.70710678, -0.83205029]]))

In [49]:
x = np.array([1.5,1.3,1.2])
y = np.array([1, 2.5, 3])
X = np.vstack([x, y])
X

array([[1.5, 1.3, 1.2],
       [1. , 2.5, 3. ]])

In [ ]:
#print(train_x)
#print(np.sum(train_x <= 0.1))
#print(np.sum(train_x >= 0.9))
#print(mean_img.shape)


# for eigendecomposition 
# check http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html 
